### ISSUE TITLE
too less location changes

### ISSUE THREAD

**Issue by slajar** [benbahrenburg/Ti.Geo.Background#4]
Hey there,

thanks for the plugin. It works pretty good but I notice pretty less location change events. I changed resolution to 10m but still it takes hundreds of meters and at least 10 minutes to update once. Can I tweak this a bit? I am on iOS right now and will do some android tests in the next days. I already have an application running with phonegap that does the trick, but I'd like to switch to Titanium.

regards
Matthias

**Comment by benbahrenburg** [comment]
This is just a sample, you need to adjust and use within your own app.

**Comment by slajar** [comment]
Well, i have a wrapper around your Api and I set the Resolution to 10 meters. There are no frequent changes. I read yor entire code but I don't understand how this Resolution handling works. Please give me pinpoint. Thanks
