### ISSUE TITLE
application sometimes closes in the background

### ISSUE THREAD

**Issue by slajar** [benbahrenburg/Ti.Geo.Background#5]
some times  I am not sure when, the app just disappears. I know it because the start button is in start state and not anymore on "stop" that means "running". Do I have to do anything here?

**Comment by benbahrenburg** [comment]
This is just a sample, you need to adjust and use within your own app.

**Comment by slajar** [comment]
Hmmpf, how shall I understand this? Isn't it the main target of this Api to have a background process running that is not interrupted/crashed/closes somehow? This behaviour in my app and in your example app makes me worry. No idea?

**Comment by benbahrenburg** [comment]
If you are new to Titanium I would recommend asking questions in the Titanium Forums at appcelerator.com or on stackoverflow.  That really is the right place to be asking "how to" questions.

This library has been adapted and used in several apps.  When working in the background there is no real one size fits all solution, you will need to adapt the code to fit your purposes.  Also keep in mind you need to use different techniques for background depending on the version of iOS you are supporting.  This example demonstrations how to implement using iOS6   You will need to implement different strategies using iOS7 and iOS8. I would recommend reading up on Significant Change events and using background "Fetch".

This code is free and available for reference, no support is provided sorry.
